Paths and file management
berenslab/retinal-rl pull request #61
Opened 2024-10-31 11:48 UTC by alex404

So this does quite a fair bit of refactoring.

- I setup the analyses in `statistics.py` to return dataclass instances to make things more manageable and readable. 
- I also made a push to a more pathlib style of directory management, in particular in the runner submodules.
- Generally going for a style where the at the top of the framework command (e.g. intialize, analyze or train) all necessary variables are extracted out of the DictConfig.
- Saving analysis results to disk was the original push for this, and that's done too.

I definitely wasn't perfectly complete or consistent with how I did this, but I think things are significantly better organized than they were before. Ideally this provides a good reference for how to factor/refactor such code in other parts of the library. Definitely open to feedback on review.x

Resolves #43

2024-10-31 11:59 UTC, alex404 commented
This probably seems more complicated than it is. The bulk of the changes are moving blocks of arguments around into dataclasses.

2024-10-31 12:02 UTC, alex404 commented
Actually hold on just discovered a bug

2024-10-31 12:09 UTC, alex404 commented
Okay seems to be fine now

2024-11-04 11:02 UTC, fabioseel reviewed
Seems mostly fine, just want to hear your comment thoughts on my comment in plot (moving the inner function out to module scope)
and in statistics (using the defined dataclasses already within the functions)

2024-11-06 10:34 UTC, alex404 commented on retinal_rl/analysis/plot.py
> +    def make_image_grid(arrays: List[FloatArray], nrow: int) -> FloatArray:
Not sure. There's a pytorch function that does this, and this is what Claude spat out when I asked it for a version that would work with numpy arrays. I can move out it though. Probably makes more sense.

2024-11-06 11:00 UTC, alex404 commented on retinal_rl/analysis/statistics.py
> +    results: Dict[str, Dict[str, Dict[float, List[FloatArray]]]] = {
Eh, not sure if changing things really helped but I did it as per request ;)

2024-11-07 14:01 UTC, fabioseel requested changes
just a minor change to avoid the duplicate code

2024-11-07 15:51 UTC, alex404 commented on retinal_rl/analysis/statistics.py
> +    for transform in imageset.source_transforms:
As you wish.

2024-11-08 10:06 UTC, fabioseel approved these changes
Looks good to me now :)

2024-11-08 10:19 UTC, merged